const mockProducts = [
  {
    _id: 'mock-1',
    name: 'Wireless Keyboard',
    price: 1499,
    ratings: 4.2,
    numOfReviews: 48,
    description: 'Compact wireless keyboard with quiet keys and long battery backup.',
    category: 'Electronics',
    stock: 20,
    images: [{ url: 'https://dummyimage.com/800x800/4A90E2/FFFFFF&text=Keyboard' }],
  },
  {
    _id: 'mock-2',
    name: 'Bluetooth Speaker',
    price: 1999,
    ratings: 4.4,
    numOfReviews: 63,
    description: 'Portable bluetooth speaker with deep bass and clear vocals.',
    category: 'Electronics',
    stock: 16,
    images: [{ url: 'https://dummyimage.com/800x800/E24A4A/FFFFFF&text=Speaker' }],
  },
  {
    _id: 'mock-3',
    name: 'Mirrorless Camera',
    price: 54999,
    ratings: 4.6,
    numOfReviews: 21,
    description: 'Beginner friendly mirrorless camera for photo and video content.',
    category: 'Cameras',
    stock: 8,
    images: [{ url: 'https://dummyimage.com/800x800/90E24A/FFFFFF&text=Camera' }],
  },
  {
    _id: 'mock-4',
    name: 'Gaming Laptop 15',
    price: 78999,
    ratings: 4.3,
    numOfReviews: 34,
    description: 'Powerful gaming laptop with high refresh rate display.',
    category: 'Laptop',
    stock: 10,
    images: [{ url: 'https://dummyimage.com/800x800/E2A04A/FFFFFF&text=Laptop' }],
  },
  {
    _id: 'mock-5',
    name: 'Noise Cancelling Headphones',
    price: 3499,
    ratings: 4.5,
    numOfReviews: 55,
    description: 'Over-ear headphones with active noise cancellation.',
    category: 'Headphones',
    stock: 25,
    images: [{ url: 'https://dummyimage.com/800x800/A04AE2/FFFFFF&text=Headphones' }],
  },
  {
    _id: 'mock-6',
    name: 'Travel Backpack',
    price: 1299,
    ratings: 4.1,
    numOfReviews: 19,
    description: 'Durable backpack with multiple compartments and laptop sleeve.',
    category: 'Accessories',
    stock: 30,
    images: [{ url: 'https://dummyimage.com/800x800/4AE2A0/FFFFFF&text=Backpack' }],
  },
  {
    _id: 'mock-7',
    name: 'JavaScript Mastery',
    price: 699,
    ratings: 4.7,
    numOfReviews: 15,
    description: 'Practical guide to modern JavaScript from basics to advanced.',
    category: 'Books',
    stock: 40,
    images: [{ url: 'https://dummyimage.com/800x800/E24AA0/FFFFFF&text=Book' }],
  },
  {
    _id: 'mock-8',
    name: 'Yoga Mat',
    price: 899,
    ratings: 4.0,
    numOfReviews: 28,
    description: 'Anti-slip yoga mat for home workout and daily sessions.',
    category: 'Sports',
    stock: 22,
    images: [{ url: 'https://dummyimage.com/800x800/E2704A/FFFFFF&text=Yoga+Mat' }],
  },
];

export default mockProducts;
